apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hello-java-do288-apps
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-maniskum-tenant/do288-apps-hello-java/hello-java-do288-apps@sha256:e5b30e5c68c29df0e066b15b5f8ae751955c193635ac78208ee3acbaf6c0c0e9
        name: container-image
        resources: {}
status: {}
