apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-java-do288-apps
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-java-do288-apps
    app.kubernetes.io/part-of: do288-apps-hello-java
  name: hello-java-do288-apps
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: hello-java-do288-apps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hello-java-do288-apps
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-maniskum-tenant/do288-apps-hello-java/hello-java-do288-apps@sha256:e5b30e5c68c29df0e066b15b5f8ae751955c193635ac78208ee3acbaf6c0c0e9
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
