apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-java-do288-apps
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-java-do288-apps
    app.kubernetes.io/part-of: do288-apps-hello-java
  name: hello-java-do288-apps
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hello-java-do288-apps
status:
  loadBalancer: {}
